2024-12-11 11:59:00 ERROR 400 response executing GraphQL.
2024-12-11 11:59:00 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-11 11:59:00 ERROR Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1120, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-11 12:01:36 ERROR 400 response executing GraphQL.
2024-12-11 12:01:36 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-11 12:01:36 ERROR Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1120, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-11 12:04:50 ERROR 400 response executing GraphQL.
2024-12-11 12:04:50 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-11 12:04:50 ERROR Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1120, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-11 12:05:51 ERROR 400 response executing GraphQL.
2024-12-11 12:05:51 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-11 12:05:51 ERROR Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1120, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-11 12:07:09 ERROR 400 response executing GraphQL.
2024-12-11 12:07:09 ERROR {"errors":[{"message":"name required for project query","path":["project"]}],"data":{"project":null}}
2024-12-11 12:07:09 ERROR Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1120, in sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 35, in wrapper
    raise CommError(message, error)
wandb.errors.errors.CommError: name required for project query (Error 400: Bad Request)

2024-12-11 12:12:48 ERROR Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1130, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
ValueError: Sweep credit_card_fraud/sweeps/ps3vtz7b not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 1677, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 572, in agent
    return run_agent(
           ^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 531, in run_agent
    agent.run()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\wandb_agent.py", line 193, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\internal.py", line 130, in sweep
    return self.api.sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 71, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 1130, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
wandb.errors.errors.CommError: Sweep credit_card_fraud/sweeps/ps3vtz7b not found

2024-12-11 12:15:52 INFO Running runs: []
2024-12-11 12:15:52 INFO Agent received command: run
2024-12-11 12:15:52 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:15:52 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:15:57 INFO Running runs: ['p179zlnr']
2024-12-11 12:16:12 INFO Cleaning up finished run: p179zlnr
2024-12-11 12:16:12 INFO Agent received command: run
2024-12-11 12:16:12 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 5
	random_state: 10
	tree_method: hist
2024-12-11 12:16:12 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=5 --random_state=10 --tree_method=hist
2024-12-11 12:16:17 INFO Running runs: ['b2on4a8w']
2024-12-11 12:18:04 INFO Running runs: []
2024-12-11 12:18:04 INFO Agent received command: run
2024-12-11 12:18:04 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:18:04 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:18:09 INFO Running runs: ['yak510vk']
2024-12-11 12:18:24 INFO Cleaning up finished run: yak510vk
2024-12-11 12:18:24 INFO Agent received command: run
2024-12-11 12:18:24 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 5
	random_state: 10
	tree_method: hist
2024-12-11 12:18:24 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=5 --random_state=10 --tree_method=hist
2024-12-11 12:18:29 INFO Running runs: ['2udlr7tz']
2024-12-11 12:20:29 INFO Running runs: []
2024-12-11 12:20:29 INFO Agent received command: run
2024-12-11 12:20:29 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:20:29 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:20:34 INFO Running runs: ['2fogldx0']
2024-12-11 12:20:49 INFO Cleaning up finished run: 2fogldx0
2024-12-11 12:20:49 INFO Agent received command: run
2024-12-11 12:20:49 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 5
	random_state: 10
	tree_method: hist
2024-12-11 12:20:49 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=5 --random_state=10 --tree_method=hist
2024-12-11 12:20:54 INFO Running runs: ['aq1ppnza']
2024-12-11 12:21:15 INFO Cleaning up finished run: aq1ppnza
2024-12-11 12:21:15 INFO Agent received command: run
2024-12-11 12:21:15 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 7
	random_state: 10
	tree_method: hist
2024-12-11 12:21:15 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=7 --random_state=10 --tree_method=hist
2024-12-11 12:21:20 INFO Running runs: ['nd83gxwq']
2024-12-11 12:21:40 INFO Cleaning up finished run: nd83gxwq
2024-12-11 12:21:40 INFO Agent received command: run
2024-12-11 12:21:40 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:21:40 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:21:45 INFO Running runs: ['yhdssf09']
2024-12-11 12:22:00 INFO Cleaning up finished run: yhdssf09
2024-12-11 12:22:01 INFO Agent received command: run
2024-12-11 12:22:01 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 5
	random_state: 10
	tree_method: hist
2024-12-11 12:22:01 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=5 --random_state=10 --tree_method=hist
2024-12-11 12:22:06 INFO Running runs: ['yzm1wtvy']
2024-12-11 12:22:26 INFO Cleaning up finished run: yzm1wtvy
2024-12-11 12:22:26 INFO Agent received command: run
2024-12-11 12:22:26 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 7
	random_state: 10
	tree_method: hist
2024-12-11 12:22:26 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=7 --random_state=10 --tree_method=hist
2024-12-11 12:22:31 INFO Running runs: ['asgv4rhq']
2024-12-11 12:22:51 INFO Cleaning up finished run: asgv4rhq
2024-12-11 12:22:52 INFO Agent received command: run
2024-12-11 12:22:52 INFO Agent starting run with config:
	booster: gblinear
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:22:52 INFO About to run command: python train.py --booster=gblinear --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:22:57 INFO Running runs: ['qjcsxo1s']
2024-12-11 12:23:37 INFO Cleaning up finished run: qjcsxo1s
2024-12-11 12:23:37 INFO Agent received command: run
2024-12-11 12:23:37 INFO Agent starting run with config:
	booster: gblinear
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 5
	random_state: 10
	tree_method: hist
2024-12-11 12:23:37 INFO About to run command: python train.py --booster=gblinear --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=5 --random_state=10 --tree_method=hist
2024-12-11 12:23:42 INFO Running runs: ['nvpzi8nd']
2024-12-11 12:24:23 INFO Cleaning up finished run: nvpzi8nd
2024-12-11 12:24:23 INFO Agent received command: run
2024-12-11 12:24:23 INFO Agent starting run with config:
	booster: gblinear
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 7
	random_state: 10
	tree_method: hist
2024-12-11 12:24:23 INFO About to run command: python train.py --booster=gblinear --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=7 --random_state=10 --tree_method=hist
2024-12-11 12:24:28 INFO Running runs: ['3p401t10']
2024-12-11 12:25:08 INFO Cleaning up finished run: 3p401t10
2024-12-11 12:25:09 INFO Agent received command: run
2024-12-11 12:25:09 INFO Agent starting run with config:
	booster: gblinear
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:25:09 INFO About to run command: python train.py --booster=gblinear --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:25:14 INFO Running runs: ['jiyc6ykg']
2024-12-11 12:31:44 INFO Running runs: []
2024-12-11 12:31:44 INFO Agent received command: run
2024-12-11 12:31:44 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:31:44 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:31:49 INFO Running runs: ['hrgylwrt']
2024-12-11 12:32:04 INFO Cleaning up finished run: hrgylwrt
2024-12-11 12:32:04 INFO Agent received command: run
2024-12-11 12:32:04 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 5
	random_state: 10
	tree_method: hist
2024-12-11 12:32:04 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=5 --random_state=10 --tree_method=hist
2024-12-11 12:32:09 INFO Running runs: ['xkt3v5vk']
2024-12-11 12:32:30 INFO Cleaning up finished run: xkt3v5vk
2024-12-11 12:32:30 INFO Agent received command: run
2024-12-11 12:32:30 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 7
	random_state: 10
	tree_method: hist
2024-12-11 12:32:30 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=7 --random_state=10 --tree_method=hist
2024-12-11 12:32:35 INFO Running runs: ['i2elqk3g']
2024-12-11 12:32:55 INFO Cleaning up finished run: i2elqk3g
2024-12-11 12:32:55 INFO Agent received command: run
2024-12-11 12:32:55 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:32:55 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:33:00 INFO Running runs: ['xmp4ckcn']
2024-12-11 12:33:15 INFO Cleaning up finished run: xmp4ckcn
2024-12-11 12:33:16 INFO Agent received command: run
2024-12-11 12:33:16 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 5
	random_state: 10
	tree_method: hist
2024-12-11 12:33:16 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=5 --random_state=10 --tree_method=hist
2024-12-11 12:33:21 INFO Running runs: ['upv61jos']
2024-12-11 12:33:41 INFO Cleaning up finished run: upv61jos
2024-12-11 12:33:41 INFO Agent received command: run
2024-12-11 12:33:41 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 7
	random_state: 10
	tree_method: hist
2024-12-11 12:33:41 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=7 --random_state=10 --tree_method=hist
2024-12-11 12:33:46 INFO Running runs: ['kr8lj0kb']
2024-12-11 12:34:01 INFO Cleaning up finished run: kr8lj0kb
2024-12-11 12:34:01 INFO Agent received command: run
2024-12-11 12:34:01 INFO Agent starting run with config:
	booster: dart
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:34:01 INFO About to run command: python train.py --booster=dart --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:34:06 INFO Running runs: ['rxefeb5x']
2024-12-11 12:42:01 ERROR 400 response executing GraphQL.
2024-12-11 12:42:01 ERROR {"errors":[{"message":"Invalid sweep config: invalid hyperparameter configuration: booster","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2024-12-11 12:42:01 ERROR Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 400, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\cli\cli.py", line 887, in sweep
    sweep_id, warnings = api.upsert_sweep(
                         ^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\internal.py", line 133, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 57, in wrapper
    raise err
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\apis\normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3340, in upsert_sweep
    raise e
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 3334, in upsert_sweep
    response = self.gql(
               ^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 372, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\sdk\lib\retry.py", line 147, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\wandb\util.py", line 880, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.errors.UsageError: Invalid sweep config: invalid hyperparameter configuration: booster

2024-12-11 12:42:57 INFO Running runs: []
2024-12-11 12:42:57 INFO Agent received command: run
2024-12-11 12:42:57 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:42:57 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:43:02 INFO Running runs: ['mittqncb']
2024-12-11 12:43:17 INFO Cleaning up finished run: mittqncb
2024-12-11 12:43:17 INFO Agent received command: run
2024-12-11 12:43:17 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 5
	random_state: 10
	tree_method: hist
2024-12-11 12:43:17 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=5 --random_state=10 --tree_method=hist
2024-12-11 12:43:22 INFO Running runs: ['jarzksn1']
2024-12-11 12:43:42 INFO Cleaning up finished run: jarzksn1
2024-12-11 12:43:43 INFO Agent received command: run
2024-12-11 12:43:43 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.1
	max_depth: 7
	random_state: 10
	tree_method: hist
2024-12-11 12:43:43 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.1 --max_depth=7 --random_state=10 --tree_method=hist
2024-12-11 12:43:48 INFO Running runs: ['dq95ryqm']
2024-12-11 12:44:08 INFO Cleaning up finished run: dq95ryqm
2024-12-11 12:44:08 INFO Agent received command: run
2024-12-11 12:44:08 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 3
	random_state: 10
	tree_method: hist
2024-12-11 12:44:08 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=3 --random_state=10 --tree_method=hist
2024-12-11 12:44:13 INFO Running runs: ['5acoqa70']
2024-12-11 12:44:28 INFO Cleaning up finished run: 5acoqa70
2024-12-11 12:44:29 INFO Agent received command: run
2024-12-11 12:44:29 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 5
	random_state: 10
	tree_method: hist
2024-12-11 12:44:29 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=5 --random_state=10 --tree_method=hist
2024-12-11 12:44:34 INFO Running runs: ['a0syrtts']
2024-12-11 12:44:49 INFO Cleaning up finished run: a0syrtts
2024-12-11 12:44:49 INFO Agent received command: run
2024-12-11 12:44:49 INFO Agent starting run with config:
	booster: gbtree
	device: cuda
	eval_metric: auc
	learning_rate: 0.3
	max_depth: 7
	random_state: 10
	tree_method: hist
2024-12-11 12:44:49 INFO About to run command: python train.py --booster=gbtree --device=cuda --eval_metric=auc --learning_rate=0.3 --max_depth=7 --random_state=10 --tree_method=hist
2024-12-11 12:44:54 INFO Running runs: ['xig396gs']
2024-12-11 12:45:10 INFO Cleaning up finished run: xig396gs
2024-12-11 12:45:10 INFO Agent received command: exit
2024-12-11 12:45:10 INFO Received exit command. Killing runs and quitting.
