wandb: Downloading large artifact train_data:latest, 72.86MB. 1 files...
wandb:   1 of 1 files downloaded.
Done. 0:0:0.3
2024-12-11 09:23:14,847 Dataset loaded successfully with shape: (1056847, 28)
2024-12-11 09:23:14,847 Preprocessing data
2024-12-11 09:23:14,847 Dropping columns
Traceback (most recent call last):
  File "C:\Users\eelil\OneDrive\Desktop\Capstone\Machine_Learning_Analysis_of_Bank_Fraud\model\train_all_models.py", line 14, in <module>
    X_train, X_test, y_train, y_test = preprocess_data(df)
                                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\OneDrive\Desktop\Capstone\Machine_Learning_Analysis_of_Bank_Fraud\model\shared_utils.py", line 48, in preprocess_data
    df.drop(drop_col, inplace=True)
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\pandas\core\frame.py", line 5581, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\pandas\core\generic.py", line 4788, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\pandas\core\generic.py", line 4830, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\eelil\.conda\envs\Machine_Learning_Analysis_of_Bank_Fraud\Lib\site-packages\pandas\core\indexes\base.py", line 7070, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['cc_num', 'job', 'trans_num', 'date'] not found in axis"
